BUG: tmp fix known issue w/ cargo/xargo in rust-sgx-sdk

diff --git a/core/Dockerfile b/core/Dockerfile
--- a/core/Dockerfile
+++ b/core/Dockerfile
@@ -26,7 +26,10 @@ cd /root/enigma-core/enigma-core/bin && ./app" > /root/compile_launch.bash
 RUN chmod +x /root/compile_launch.bash
 
 # Agressive build: we build it even it fails. Will always return true
-RUN cd enigma-core/enigma-core && . /opt/sgxsdk/environment && . /root/.cargo/env && SGX_MODE=$SGX_MODE RUSTFLAGS=-Awarnings make || true
+# Accounts for a known problem with cargo and xargo with the underlying rust-sgx-sdk
+RUN cd enigma-core/enigma-core && . /opt/sgxsdk/environment && . /root/.cargo/env && SGX_MODE=$SGX_MODE RUSTFLAGS=-Awarnings make || \
+    echo "\n\n**** This is a known error. Ignore for now. Will succeed upon retry ***\n" && \
+    rm -rf /root/.cargo/git/checkouts/rust-sgx-sdk-fc8771c5c45bde9a/378a4f0/xargo/ && SGX_MODE=$SGX_MODE RUSTFLAGS=-Awarnings make || true
 
 ENTRYPOINT ["/usr/bin/env"]
 CMD ["/bin/bash","-c","./compile_launch.bash; bash"]
